FROM cfplatformeng/marman:0.4.2 AS marman
FROM amidos/dcind:2.1.0

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk update && \
    apk add bats jq libc6-compat nodejs npm
COPY --from=marman /usr/local/bin/marman /usr/local/bin/
